import Foundation

/// One physical key position, matching the schema used by
/// `nickcoutsos/keymap-editor-contrib` keyboard-data files.
///
/// `row`/`col` drive the text layout of the rendered `bindings` block;
/// `x`/`y`/`w`/`h` drive the on-screen keyboard. Both are optional in the
/// source data, so both have defaults.
public struct KeyPosition: Codable, Equatable, Sendable {
    public var row: Int?
    public var col: Int?
    public var x: Double
    public var y: Double
    public var w: Double?
    public var h: Double?
    /// Rotation in degrees, with optional rotation origin.
    public var r: Double?
    public var rx: Double?
    public var ry: Double?

    public init(
        row: Int? = nil, col: Int? = nil, x: Double, y: Double,
        w: Double? = nil, h: Double? = nil,
        r: Double? = nil, rx: Double? = nil, ry: Double? = nil
    ) {
        self.row = row
        self.col = col
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        self.r = r
        self.rx = rx
        self.ry = ry
    }

    public var width: Double { w ?? 1 }
    public var height: Double { h ?? 1 }
}

/// A named layout variant within a keyboard definition.
public struct LayoutVariant: Codable, Equatable, Sendable {
    public var name: String?
    public var description: String?
    public var autoGenerated: Bool?
    public var layout: [KeyPosition]

    public init(name: String?, description: String? = nil, autoGenerated: Bool? = nil, layout: [KeyPosition]) {
        self.name = name
        self.description = description
        self.autoGenerated = autoGenerated
        self.layout = layout
    }
}

/// A keyboard definition: `keyboard-data/<id>.json`, or a repo's `config/info.json`.
public struct KeyboardDefinition: Codable, Equatable, Sendable {
    public var id: String?
    public var name: String?
    public var layouts: [String: LayoutVariant]

    public init(id: String?, name: String?, layouts: [String: LayoutVariant]) {
        self.id = id
        self.name = name
        self.layouts = layouts
    }

    /// Preferred variant: `default_transform` when present, else the first by name.
    public var defaultLayout: LayoutVariant? {
        layouts["default_transform"] ?? layouts.keys.sorted().first.flatMap { layouts[$0] }
    }
}

/// A catalog entry from `keyboard-catalog.json`.
public struct CatalogEntry: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var name: String

    public init(id: String, name: String) {
        self.id = id
        self.name = name
    }
}
